import type {XuanxueRule} from './types.js';
import {buildHelpText} from './engine/help.js';

/**
 * 玄学插件规则注册表。
 * 新增规则时填写 helpEntry 字段即可自动出现在「玄学帮助」列表中。
 */
export const xuanxueRules: XuanxueRule[] = [
    {
        name: 'xuanxue-help',
        keyword: ['玄学帮助', '玄学指令', '算命帮助'],
        matchMode: 'exact',
        url: '',
        method: 'GET',
        parse: {mode: 'text'},
        replyMode: 'forward',
        forwardTitle: '🔮 玄学功能指令一览',
        forwardNickname: '玄学助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        // usage 由 buildHelpText() 在运行时动态生成，此处仅占位
        get usage() {
            return buildHelpText(xuanxueRules);
        },
    },
    {
        name: 'xuanxue-bazi-calc',
        keyword: ['八字测算', '八字测命'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/cesuan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=1&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'baziHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字测算结果',
        forwardNickname: '八字测算助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔮 八字测算\n\n八字，即生辰八字，是一个人出生时的干支历日期，由年柱、月柱、日柱、时柱各两个字组成，共八个字，故称"四柱八字"。八字测算是中国最正统的命理方法之一，通过分析五行生克、十神关系与大运流年，推演一个人的性格、运势与人生走向。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，八字只需精确到时辰范围；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n八字测算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字测算 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🧬 八字测算 — 分析生辰八字、五行命理',
        helpCategory: '八字命理',
        replyTemplate:
            '🔮 八字测算结果\n姓名：{{name}}\n性别：{{sexInput}}\n历法：{{typeInput}}\n生辰：{{year}}-{{month}}-{{day}} {{hours}}:{{minute}}\n\n{{result}}\n\n💡 指令格式：八字测算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分',
    },
    {
        name: 'xuanxue-bazi-daily-fortune',
        keyword: ['八字每日运势', '每日八字运势', '八字今日运势'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/baziyunshi_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=1&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'baziHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字每日运势',
        forwardNickname: '每日运势助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '📆 八字每日运势\n\n八字每日运势以生辰八字为基，结合当日干支流日对命盘的影响，推算当天的吉凶方向、宜忌事项与各项运势分值。八字由年柱、月柱、日柱、时柱组成，每柱含天干地支各一字，共八字，四柱交错间藏有流年、流月、流日对命主的实时影响。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n八字每日运势 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字每日运势 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '📆 八字每日运势 — 当日宜忌、幸运信息与分项运势',
        helpCategory: '八字命理',
        replyTemplate:
            '📆 八字每日运势\n姓名：{{name}}\n性别：{{sexInput}}\n历法：{{typeInput}}\n生辰：{{year}}-{{month}}-{{day}} {{hours}}:{{minute}}\n\n{{result}}\n\n💡 指令格式：八字每日运势 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分',
    },
    {
        name: 'xuanxue-bazi-hehun',
        keyword: ['八字合婚', '合婚测算', '合婚配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/hehun_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        // 格式：男方姓名 历法 年 月 日 时 分 女方姓名 历法 年 月 日 时 分
        body: 'male_name={{male_name}}&male_type={{male_type}}&male_year={{male_year}}&male_month={{male_month}}&male_day={{male_day}}&male_hours={{male_hours}}&male_minute={{male_minute}}&female_name={{female_name}}&female_type={{female_type}}&female_year={{female_year}}&female_month={{female_month}}&female_day={{female_day}}&female_hours={{female_hours}}&female_minute={{female_minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
            required: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
        },
        parse: {
            mode: 'heHunHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字合婚结果',
        forwardNickname: '八字合婚助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💑 八字合婚\n\n八字合婚是中国传统婚配习俗，以男女双方生辰八字为依据，通过五行生克、日柱相合、年支六合六冲等关系综合评判两人的婚配契合度，给出评分与各维度分析。合婚并无绝对好坏，重在了解双方命理结构的互补与冲突。\n\n用法说明：\n1) 分别输入男方与女方信息，历法支持公历和农历；\n2) 历法填写"公历"或"农历"，性别填写"男"或"女"；\n3) 时分精确到时辰范围即可，不确定分钟可填 0。\n\n📌 指令格式：\n八字合婚 男方姓名 历法(公历/农历) 年 月 日 时 分 女方姓名 历法 年 月 日 时 分\n\n💡 示例：\n八字合婚 王小二 公历 2005 12 23 8 37 李大炮 公历 2005 5 23 8 37',
        helpEntry: '💑 八字合婚 — 男女双方八字配对合婚评分',
        helpCategory: '合盘配对',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-hepan',
        keyword: ['八字合盘', '合盘测算', '合盘配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/hepan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        // 格式：甲方姓名 历法 年 月 日 时 分 乙方姓名 历法 年 月 日 时 分
        body: 'male_name={{male_name}}&male_type={{male_type}}&male_year={{male_year}}&male_month={{male_month}}&male_day={{male_day}}&male_hours={{male_hours}}&male_minute={{male_minute}}&female_name={{female_name}}&female_type={{female_type}}&female_year={{female_year}}&female_month={{female_month}}&female_day={{female_day}}&female_hours={{female_hours}}&female_minute={{female_minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
            required: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
        },
        parse: {
            mode: 'hePanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字合盘结果',
        forwardNickname: '八字合盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🤝 八字合盘\n\n八字合盘与合婚类似，以双方生辰八字为基础，从本命卦的角度对两人进行命理合盘，分析天干地支间的生克制化关系，推演两人合作、缘分与相处中的吉凶走向。合盘不分性别，适用于朋友、搭档等各类关系的参考分析。\n\n用法说明：\n1) 分别输入甲方与乙方信息，历法支持公历和农历；\n2) 历法填写"公历"或"农历"，性别填写"男"或"女"；\n3) 时分精确到时辰范围即可，不确定分钟可填 0。\n\n📌 指令格式：\n八字合盘 甲方姓名 历法(公历/农历) 年 月 日 时 分 乙方姓名 历法 年 月 日 时 分\n\n💡 示例：\n八字合盘 王小二 公历 2005 12 23 8 37 李大炮 公历 2005 12 23 8 37',
        helpEntry: '🤝 八字合盘 — 双方本命卦与八字关系综合合盘评分',
        helpCategory: '合盘配对',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-jingsuan',
        keyword: ['八字精算', '精算八字'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/jingsuan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn&sect=2',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'baziHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字精算结果',
        forwardNickname: '八字精算助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔮 八字精算\n\n八字精算是在四柱八字基础上进行深度命盘解读的命理方法。除基本五行分析外，还包含喜用神推断、大运十年段走势、流年吉凶及财运姻缘细批。喜用神是命主五行最需要、最有助益的那个元素，大运则是每十年一换的重要运程阶段，两者结合可帮助准确把握人生关键节点。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n八字精算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字精算 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🔮 八字精算 — 深度命盘解读（喜用神/大运/流年）',
        helpCategory: '八字命理',
        replyTemplate:
            '🔮 八字精算结果\n姓名：{{name}}\n性别：{{sexInput}}\n历法：{{typeInput}}\n生辰：{{year}}-{{month}}-{{day}} {{hours}}:{{minute}}\n\n{{result}}\n\n💡 指令格式：八字精算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分',
    },
    {
        name: 'xuanxue-bazi-paipan',
        keyword: ['八字排盘', '四柱排盘', '排八字'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/paipan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn&sect=1',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'paipanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '四柱八字排盘结果',
        forwardNickname: '八字排盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧮 四柱八字排盘\n\n四柱八字排盘是将一个人出生的年、月、日、时四个时间维度，各以天干地支两个字表示，形成"年柱、月柱、日柱、时柱"，共八字，即为命盘的基础骨架。排盘可呈现大运起运时间、各柱干支详情及地支藏干等原始命盘数据，是深入命理研究的基础工具。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 八字日界线以晚上 23 时为界，23 时之后出生按次日命盘计算；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n八字排盘 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字排盘 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🧮 八字排盘 — 生成四柱命盘与大运排盘',
        helpCategory: '八字命理',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-jingpan',
        keyword: ['八字流盘', '四柱流盘', '八字精盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/jingpan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn&sect=2',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'jingpanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '四柱八字流盘结果',
        forwardNickname: '八字流盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🌊 四柱八字流盘\n\n八字流盘在四柱原盘基础上，叠加大限、流年、流月等时间层次，动态展示命盘在不同时间段的运势变化。流盘中还包含胎元、命宫、身宫等特殊信息，是观察命主当前运势走向与年月吉凶的重要参考工具。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 八字日界线以晚上 23 时为界，23 时之后出生按次日命盘计算；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n八字流盘 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字流盘 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🌊 八字流盘 — 查看流年流月与胎命身精盘',
        helpCategory: '八字命理',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-caiyun',
        keyword: ['八字流年财运分析', '流年财运分析', '八字财运分析'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/caiyunfenxi_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=2&liu_year={{liu_year}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'liu_year'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'liu_year'],
        },
        parse: {
            mode: 'caiyunHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字流年财运分析结果',
        forwardNickname: '流年财运助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💰 八字流年财运分析\n\n流年财运分析以生辰八字为根，对指定年份的财星旺衰、财运等级与漏财风险进行推演，同时提供该年度十二个月的逐月财运走势建议。财星分为正财与偏财，命主身强身弱不同，财星的喜忌也不同，需结合整体命盘综合判断。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 目标年份填写您想了解财运的具体年份；\n3) 时分精确到时辰范围即可，不确定分钟可填 0。\n\n📌 指令格式：\n八字流年财运分析 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分 目标年份\n\n💡 示例：\n八字流年财运分析 王羲之 男 公历 2005 12 23 8 37 2026',
        helpEntry: '💰 八字流年财运分析 — 年度财运评分与每月投资提示',
        helpCategory: '八字命理',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-weilai',
        keyword: ['八字未来运势', '未来运势', '八字未来'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/weilai_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=2&yunshi_year={{yunshi_year}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'yunshi_year'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'yunshi_year'],
        },
        parse: {
            mode: 'weilaiHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字未来运势结果',
        forwardNickname: '未来运势助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔭 八字未来运势\n\n八字未来运势以命主生辰八字与指定年份的流年干支为核心，综合推演事业、学业、姻缘、财运、健康五大维度在该年度的整体走向，给出年度总论与各方向评级。流年干支每年更替，与命盘原局产生新的生克变化，从而引发当年的运势起伏。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 目标年份填写您想预测运势的具体年份；\n3) 时分精确到时辰范围即可，不确定分钟可填 0。\n\n📌 指令格式：\n八字未来运势 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分 目标年份\n\n💡 示例：\n八字未来运势 王羲之 男 公历 2005 12 23 8 37 2027',
        helpEntry: '🔭 八字未来运势 — 指定年份运势五维分析（事业/财运/姻缘等）',
        helpCategory: '八字命理',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-ziwei-paipan',
        keyword: ['紫微排盘', '紫微斗数', '紫微命盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/zwpan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn&sect=2',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'zwpanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '紫微排盘结果',
        forwardNickname: '紫微斗数助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '⭐ 紫微排盘\n\n紫微斗数是中国古代重要的星命学体系，以出生年月日时推算出紫微星落于哪个宫位，进而以十四主星布满十二宫，分析命宫、财帛宫、官禄宫、夫妻宫等各宫的星群组合，推演命主的性格特质、事业走向与人生吉凶。紫微斗数与八字并列为中国命理两大支柱。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 命理日界为晚 23:00，23 点之后出生按次日计算命盘；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n紫微排盘 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n紫微排盘 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '⭐ 紫微排盘 — 紫微斗数十二宫命盘及各宫简批',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-ziwei-liupan',
        keyword: ['紫微流盘', '紫微流排盘', '紫微流年盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/zwlpan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'zwpanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '紫微流盘结果',
        forwardNickname: '紫微流盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🌌 紫微流盘\n\n紫微流盘在先天本命盘基础上，叠加大限（每十年一换的运程阶段）、流年、流月、流日、流时五个时间层次，动态观察各时间段内星曜会照与宫位力量的变化。流盘是紫微斗数中判断近期运势走向与具体事件时机的核心工具。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 命理日界通常以晚 23:00 为界，23 点后按次日计算；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n紫微流盘 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n紫微流盘 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🌌 紫微流盘 — 紫微先天盘与大限流年流月流日流时',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-qimen-paipan',
        keyword: ['奇门排盘', '奇门遁甲', '奇门盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/qimen_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&ju_model=0&an_gan_method=1&pan_model=0&fei_pan_model=1&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&manual_ju=0&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'qimenHtml',
        },
        replyMode: 'forward',
        forwardTitle: '奇门排盘结果',
        forwardNickname: '奇门遁甲助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧿 奇门排盘\n\n奇门遁甲是中国古代三大神数之一，以天时（节气）为基，将天盘九星、地盘九宫、八门、八神按时间布局，推演当下时空的吉凶方位与事态走向。古人用奇门遁甲决策军事、出行、择日等重要事务，现代则多用于占事判断与趋势分析。\n\n用法说明：\n1) 输入的年月日时分是【当前占问时间】，不是出生日期；\n2) 公历即阳历，农历即阴历，请按实际类型输入；\n3) 命理日界通常以晚 23:00 为界，若不确定分钟可填 0。\n\n📌 指令格式：\n奇门排盘 姓名 性别(男/女) 历法(公历/农历) 起盘年 月 日 时 分\n\n💡 示例：\n奇门排盘 王羲之 男 公历 2026 5 11 14 30',
        helpEntry: '🧿 奇门排盘 — 奇门遁甲九宫盘与门局简批',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-yinpan-qimen-paipan',
        keyword: ['阴盘奇门排盘', '阴盘奇门', '阴盘遁甲'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/yinpanqimen_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&pan_model=0&ke_sect=0&ju_model=0&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'qimenHtml',
        },
        replyMode: 'forward',
        forwardTitle: '阴盘奇门排盘结果',
        forwardNickname: '阴盘奇门助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🕳 阴盘奇门排盘\n\n阴盘奇门遁甲（道家阴盘）是奇门遁甲的另一流派，与通行的阳盘奇门并称"奇门双雄"。阴盘以星为主、门为辅，强调天时与地气的阴阳流转，常用于风水趋势判断、行为决策辅助与个人方位宜忌分析，是道家实用术数的重要组成部分。\n\n用法说明：\n1) 输入的年月日时分是【当前占问时间】，不是出生日期；\n2) 公历即阳历，农历即阴历，请按实际类型输入；\n3) 命理日界通常以晚 23:00 为界，若不确定分钟可填 0。\n\n📌 指令格式：\n阴盘奇门排盘 姓名 性别(男/女) 历法(公历/农历) 起盘年 月 日 时 分\n\n💡 示例：\n阴盘奇门排盘 王羲之 男 公历 2026 5 11 14 30',
        helpEntry: '🕳 阴盘奇门排盘 — 阴盘九宫盘与门局简批',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-xingzuo-xingpan',
        keyword: ['星座星盘', '西洋星盘', '占星星盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/xingpan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&longitude_degree={{longitude_degree}}&longitude_minutes={{longitude_minutes}}&longitude_type={{longitude_type}}&latitude_degree={{latitude_degree}}&latitude_minutes={{latitude_minutes}}&latitude_type={{latitude_type}}&timezone={{timezone}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&isdst={{isdst}}',
        args: {
            mode: 'regex',
            // 示例：王羲之 男 公历 2005 12 23 8 37 120°23′E 36°4′N 8 0
            pattern: '^\\s*(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\d{4})\\s+(\\d{1,2})\\s+(\\d{1,2})\\s+(\\d{1,2})\\s+(\\d{1,2})\\s+(\\d{1,3})\\s*[°º]\\s*(\\d{1,2})\\s*[′’`\'‘]?\\s*([EeWw])\\s+(\\d{1,2})\\s*[°º]\\s*(\\d{1,2})\\s*[′’`\'‘]?\\s*([NnSs])(?:\\s+([+-]?\\d{1,2}(?:\\.5)?))?(?:\\s+([01]))?\\s*$',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'longitude_degree', 'longitude_minutes', 'longitude_type', 'latitude_degree', 'latitude_minutes', 'latitude_type', 'timezone', 'isdst'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'longitude_degree', 'longitude_minutes', 'longitude_type', 'latitude_degree', 'latitude_minutes', 'latitude_type'],
        },
        parse: {
            mode: 'xingpanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '星座星盘结果',
        forwardNickname: '星盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '✨ 星座星盘\n\n西洋星盘（占星学）以出生时间和出生地地理坐标为依据，计算出太阳、月亮及八大行星在黄道十二星座中的落位，结合十二宫位与行星相位，分析一个人的性格底色、人生课题与运势周期。与中国命理不同，西洋占星同时注重出生地经纬度对命盘的影响。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际类型输入；\n2) 需要出生地经纬度，格式如 120°23′E 36°4′N；\n3) 时区默认东八区（填 8），夏令时默认否（填 0），可省略不填。\n\n📌 指令格式：\n星座星盘 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分 经度(度分方向) 纬度(度分方向) [时区] [isdst]\n\n💡 示例：\n星座星盘 王羲之 男 公历 2005 12 23 8 37 120°23′E 36°4′N\n星座星盘 王羲之 男 公历 2005 12 23 8 37 120°23′E 36°4′N 8 0',
        helpEntry: '✨ 星座星盘 — 星体落座、宫位、相位与四轴解读',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-daliuren-paipan',
        keyword: ['大六壬排盘', '六壬排盘', '大六壬'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/daliuren_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&gui_model=1&gui_xing_model=2&pei_model=0&born_year={{born_year}}&hang_year=1&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'born_year', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'born_year', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'daliurenHtml',
        },
        replyMode: 'forward',
        forwardTitle: '大六壬排盘结果',
        forwardNickname: '大六壬助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧭 大六壬排盘\n\n大六壬是中国古代三大神数之一（与奇门遁甲、太乙神数并列），以月将、行年、时辰三者为核心，起出天地盘、四课三传，结合神将吉凶推演所问之事的吉凶发展脉络。古代占卜、诉讼、出行、商贸等皆可用大六壬判断时机与走向，是传统术数中精密度极高的预测体系。\n\n用法说明：\n1) 需要两组年份：出生年 + 本次占问的起盘日期时间；\n2) 公历即阳历，农历即阴历，请按实际类型输入；\n3) 命理日界通常以晚 23:00 为界，若不确定分钟可填 0。\n\n📌 指令格式：\n大六壬排盘 姓名 性别(男/女) 历法(公历/农历) 出生年 起盘年 月 日 时 分\n\n💡 示例：\n大六壬排盘 王羲之 男 公历 2005 2026 5 11 14 30\n（其中 2005 是出生年；2026-5-11 14:30 是起盘日期）',
        helpEntry: '🧭 大六壬排盘 — 大六壬天地神盘与三传简批',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-meiri',
        keyword: ['每日一占', '每日占卜', '小六壬占卜'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/zhanbu/meiri_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '每日一占结果',
        forwardNickname: '占卜助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧿 每日一占\n\n卜卦方法：静默一分钟，心念集中于所测之事（爱情/事业/健康等），然后心念一动，发送指令后查看卦辞并体会吉凶指示。\n\n摇卦简介：\n1) 每日占卜使用小六壬占卜法，摇卦贵在随机而动；\n2) 不急不占，无事不占，不动不占；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n每日一占\n\n💡 示例：\n每日一占',
        helpEntry: '🧿 每日一占 — 小六壬随机摇卦解读',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-taluo',
        keyword: ['塔罗牌占卜', '塔罗占卜', '塔罗牌'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/zhanbu/taluo_result/id/0.html',
        method: 'GET',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '塔罗牌占卜结果',
        forwardNickname: '塔罗占卜助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔮 塔罗牌占卜\n\n塔罗牌是西方古老占卜工具，被称为“大自然的奥秘库”。此玩法为单张牌占卜，适合快速查看当前主题指示。\n\n塔罗牌简介：\n1) 大阿卡那共 22 张，常用于观察阶段性主线与运势方向；\n2) 单张牌占卜法简单直观，适用于多数主题；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n塔罗牌占卜\n\n💡 示例：\n塔罗牌占卜',
        helpEntry: '🃏 塔罗牌占卜 — 单张塔罗牌解读与神谕提示',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-yaoguai',
        keyword: ['摇卦占卜', '摇卦', '金钱卦', '易经占卜'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/zhanbu/result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '摇卦占卜结果',
        forwardNickname: '摇卦助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🪙 摇卦占卜\n\n金钱卦是六爻占卜中的简易算法，以铜钱随机摇卦，得六十四卦之一，用以占卜吉凶。\n\n卜卦方法：\n1) 静默一分钟，心念集中于所测之事（爱情/事业/健康等）；\n2) 心念一动，发送指令即随机掷出金钱卦；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n摇卦占卜\n\n💡 示例：\n摇卦占卜',
        helpEntry: '🪙 摇卦占卜 — 随机掷出六十四卦，查看卦辞吉凶',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-zhiwen',
        keyword: ['指纹占卜', '指纹测算'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/zhanbu/zhiwen_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'muzhi={{muzhi}}&shizhi={{shizhi}}&zhongzhi={{zhongzhi}}&wumingzhi={{wumingzhi}}&xiaozhi={{xiaozhi}}',
        args: {
            mode: 'regex',
            // 匹配5位由0/1组成的字符串，如：01010 或 0 1 0 1 0
            pattern: '^\\s*([01])[\\s,，]*([01])[\\s,，]*([01])[\\s,，]*([01])[\\s,，]*([01])\\s*$',
            names: ['muzhi', 'shizhi', 'zhongzhi', 'wumingzhi', 'xiaozhi'],
            required: ['muzhi', 'shizhi', 'zhongzhi', 'wumingzhi', 'xiaozhi'],
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '指纹占卜结果',
        forwardNickname: '指纹占卜助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🖐 指纹占卜\n\n根据指纹形状测算性格与命运，男性测左手，女性测右手。指纹分两类：\n• 箩纹（斗纹）= 0 — 同心圆/螺旋状，外围闭合\n• 簸箕纹（流纹）= 1 — 开口如高山流水状\n\n📌 指令格式：\n指纹占卜 大拇指 食指 中指 无名指 小指\n（每指输入 0=箩纹 或 1=簸箕纹，可连写或空格分隔）\n\n💡 示例：\n指纹占卜 01010\n指纹占卜 0 1 0 1 0',
        helpEntry: '🖐 指纹占卜 — 根据五指指纹形状解读性格与命运',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-guanyin',
        keyword: ['观音灵签', '观音抽签', '观音签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/guanyin_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '观音灵签结果',
        forwardNickname: '观音灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🪷 观音灵签\n\n抽签前双手合十，默念【救苦救难观音菩萨】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽取灵签并查看签辞。\n\n抽签简介：\n1) 观音灵签为民间常见签种，共百签，各地签文略有差异但解意大致相通；\n2) 观世音菩萨象征慈悲与智慧，签辞多用于启示与劝勉；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n观音灵签\n\n💡 示例：\n观音灵签',
        helpEntry: '🪷 观音灵签 — 抽取观音签辞并查看解签信息',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-yuelao',
        keyword: ['月老灵签', '月老抽签', '月老签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/yuelao_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '月老灵签结果',
        forwardNickname: '月老灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💘 月老灵签\n\n抽签前双手合十，默念【月下老人诚求指示】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽签并查看签辞。\n\n抽签简介：\n1) 月老灵签为民间常见签种，共百签，签文流传久远，各地略有差异但解意大致相通；\n2) 月下老人是民间传说中的婚姻之神（红喜神/媒神），多用于姻缘指引；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n月老灵签\n\n💡 示例：\n月老灵签',
        helpEntry: '💘 月老灵签 — 抽取月老签辞并查看解签提示',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-fozu',
        keyword: ['佛祖灵签', '佛祖抽签', '佛祖签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/fozu_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '佛祖灵签结果',
        forwardNickname: '佛祖灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🙏 佛祖灵签\n\n抽签前双手合十，默念【南无阿弥陀佛】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽签并查看签辞。\n\n抽签简介：\n1) 佛祖灵签为民间常见签种，共五十一签，签文流传久远，各地略有差异但解意大致相通；\n2) 释迦摩尼为佛教创始人，被尊称佛祖，签辞多用于启示与劝诫；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n佛祖灵签\n\n💡 示例：\n佛祖灵签',
        helpEntry: '🙏 佛祖灵签 — 抽取佛祖签辞并查看解签信息',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-zhuge',
        keyword: ['诸葛灵签', '诸葛抽签', '诸葛签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/zhuge_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '诸葛灵签结果',
        forwardNickname: '诸葛灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧭 诸葛灵签\n\n抽签前双手合十，默念【诸葛仙师指点迷经】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽取灵签并查看签辞。\n\n抽签简介：\n1) 诸葛灵签为民间常见签种，共百签，签文流传久远，各地略有差异但解意大致相通；\n2) 诸葛亮以料事与谋略著称，诸葛神签常用于占卜吉凶祸福；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n诸葛灵签\n\n💡 示例：\n诸葛灵签',
        helpEntry: '🧭 诸葛灵签 — 抽取诸葛签辞并查看解签提示',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-mazu',
        keyword: ['妈祖灵签', '妈祖抽签', '妈祖签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/mazu_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '妈祖灵签结果',
        forwardNickname: '妈祖灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '⛵ 妈祖灵签\n\n抽签前双手合十，默念【妈祖圣母指点迷经】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽签并查看签辞。\n\n抽签简介：\n1) 妈祖灵签为民间常见签种，共六十签，签文流传久远，各地略有差异但解意大致相通；\n2) 妈祖（天后圣母）在民间信仰中象征护佑与指引，签辞多用于启示吉凶祸福；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n妈祖灵签\n\n💡 示例：\n妈祖灵签',
        helpEntry: '⛵ 妈祖灵签 — 抽取妈祖签辞并查看解签提示',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-lvzu',
        keyword: ['吕祖灵签', '吕祖抽签', '吕祖签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/lvzu_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '吕祖灵签结果',
        forwardNickname: '吕祖灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🗡 吕祖灵签\n\n抽签前双手合十，默念【吕祖仙师指点迷经】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽签并查看签辞。\n\n抽签简介：\n1) 吕祖灵签为民间常见签种，共百签，签文流传久远，各地略有差异但解意大致相通；\n2) 吕洞宾（纯阳子）为道教重要祖师之一，吕祖神签常用于占卜吉凶祸福；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n吕祖灵签\n\n💡 示例：\n吕祖灵签',
        helpEntry: '🗡 吕祖灵签 — 抽取吕祖签辞并查看解签信息',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-jinkoujue-paipan',
        keyword: ['金口诀排盘', '金口诀', '金口决排盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/jinkoujue_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&jiang_model=0&gui_model=1&gui_xing_model=2&difen_model=3&difen_model_value1=子&difen_model_value2=&born_year={{born_year}}&hang_year=1&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'born_year', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'born_year', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'jinkoujueHtml',
        },
        replyMode: 'forward',
        forwardTitle: '金口诀排盘结果',
        forwardNickname: '金口诀助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '📜 金口诀排盘\n\n金口诀（又称御定六壬神课）是在大六壬基础上简化发展而来的预测方法，以人元（出生年）、贵神（占问时辰的神将）、将神（月将）、地分（日干所在地支）四位为核心，通过四位之间的生克关系推演所问之事的吉凶趋势，是民间广泛流传的实用占课工具。\n\n用法说明：\n1) 需要两组年份：出生年 + 本次占问的起盘日期时间；\n2) 公历即阳历，农历即阴历，请按实际类型输入；\n3) 命理日界通常以晚 23:00 为界，若不确定分钟可填 0。\n\n📌 指令格式：\n金口诀排盘 姓名 性别(男/女) 历法(公历/农历) 出生年 起盘年 月 日 时 分\n\n💡 示例：\n金口诀排盘 王羲之 男 公历 2005 2026 5 11 14 30',
        helpEntry: '📜 金口诀排盘 — 金口诀四位（人元/贵神/将神/地分）',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-meihua-paipan',
        keyword: ['梅花易数排盘', '梅花易数', '梅花排盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/meihua_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'born_year={{born_year}}&pan_model=1&gua_yao6=0&gua_yao5=0&gua_yao4=0&gua_yao3=0&gua_yao2=0&gua_yao1=0&number=&number_up=&number_down=&yao_add_time=1&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['born_year', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['born_year', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'meihuaHtml',
        },
        replyMode: 'forward',
        forwardTitle: '梅花易数排盘结果',
        forwardNickname: '梅花易数助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🌸 梅花易数排盘\n\n梅花易数是宋代邵雍所创的易学预测方法，以先天八卦数理为基础，通过起卦时间（年月日时）或随机数字起出主卦、互卦、变卦，以卦象体用生克及五行旺衰分析所问之事的吉凶走向。梅花易数贵在随机而起、心思所动即为卦象，是"心易"的重要代表。\n\n用法说明：\n1) 需要两组年份：出生年 + 本次起卦的时间（占问时间）；\n2) 起卦时间是当前占问时间，不是出生日期；\n3) 若不确定分钟可填 0。\n\n📌 指令格式：\n梅花易数排盘 出生年 起卦年 月 日 时 分\n\n💡 示例：\n梅花易数排盘 2005 2026 12 23 8 37',
        helpEntry: '🌸 梅花易数排盘 — 主卦/互卦/变卦与卦辞解读',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-liuyao-paipan',
        keyword: ['六爻排盘', '六爻起卦', '六爻预测'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/liuyao_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'born_year={{born_year}}&pan_model=1&gua_yao6=0&gua_yao5=0&gua_yao4=0&gua_yao3=0&gua_yao2=0&gua_yao1=0&number=&number_up=&number_down=&yao_add_time=1&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['born_year', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['born_year', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'liuyaoHtml',
        },
        replyMode: 'forward',
        forwardTitle: '六爻排盘结果',
        forwardNickname: '六爻排盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧿 六爻排盘\n\n六爻预测源自《易经》，以金钱卦（铜钱摇卦）或时间数字起卦，得六十四卦之一，每卦含六条爻，配以六亲（父母、兄弟、子孙、官鬼、妻财）与六神（青龙、朱雀、勾陈、螣蛇、白虎、玄武），通过分析旺衰、动变、飞伏关系，判断所求之事的吉凶与时间节点。六爻是中国民间应用最广泛的预测方法之一。\n\n用法说明：\n1) 需要两组年份：出生年 + 本次起卦的时间（占问时间）；\n2) 起卦时间是当前占问时间，不是出生日期；\n3) 若不确定分钟可填 0。\n\n📌 指令格式：\n六爻排盘 出生年 起卦年 月 日 时 分\n\n💡 示例：\n六爻排盘 2005 2026 12 23 8 37',
        helpEntry: '🧿 六爻排盘 — 六神六亲主变卦与卦辞解读',
        helpCategory: '玄学排盘',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-jiuxing-suanming',
        keyword: ['九星算命', '九星测算', '九星命相'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/jiuxing_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'jiuxingHtml',
        },
        replyMode: 'forward',
        forwardTitle: '九星算命结果',
        forwardNickname: '九星算命助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔯 九星算命\n\n九星算命源自玄空风水的九星命相体系，以出生年份推算出命主所属的九宫星位。九星包括一白水星、二黑土星、三碧木星、四绿木星、五黄土星、六白金星、七赤金星、八白土星、九紫火星，每种星位对应不同的性格特质、运势机缘与人际关系宜忌，需结合风水方位综合运用。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n九星算命 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n九星算命 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🔯 九星算命 — 九星命相与风水命运测算',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-shengri-lunming',
        keyword: ['生日论命', '生日测算', '生日书'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/shengri_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'month={{month}}&day={{day}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['month', 'day'],
            required: ['month', 'day'],
        },
        parse: {
            mode: 'shengriHtml',
        },
        replyMode: 'forward',
        forwardTitle: '生日论命结果',
        forwardNickname: '生日论命助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🎂 生日论命\n\n生日论命依据《生日书》与西洋星相命理，以公历月日为核心，对每一天出生的人进行性格特质、潜在才能、健康倾向与人生建议的系统分析。每个人的生日对应特定的星座宫度与塔罗原型，凭借出生日期可窥见内在性格与潜在力量，不同的生日都有各自独特的命运启示。\n\n用法说明：\n1) 仅需输入公历月份和日期，无需填写年份；\n2) 月份和日期以空格分隔输入即可。\n\n📌 指令格式：\n生日论命 公历月 公历日\n\n💡 示例：\n生日论命 12 31',
        helpEntry: '🎂 生日论命 — 按生日查看性格、健康与运势启示',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-jiehun-yuce',
        keyword: ['结婚预测', '结婚测算', '鬼谷十星'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/yuce/jiehun_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'jiehunHtml',
        },
        replyMode: 'forward',
        forwardTitle: '结婚预测结果',
        forwardNickname: '结婚预测助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💍 结婚预测\n\n结婚预测以鬼谷子十星命理为基础，通过出生年月日时推算命主所属十大主星，进而预测桃花旺盛年龄、情感空窗期、恋爱性格与宿命伴侣特质。鬼谷子约两千三百年前在研究天文星象时发现星象与命运的关联，由此钻研出独具特色的命理体系，十星分别对应不同的情感模式与人生节律。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n结婚预测 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n结婚预测 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '💍 结婚预测 — 鬼谷十星推算桃花运盛龄与恋爱性格',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-xingzuo-daily',
        keyword: ['星座运势', '今日星座运势', '星座今日运势'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/public/xingzuo/id/{{xingzuo_id}}.html',
        method: 'GET',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
        args: {
            mode: 'split',
            names: ['xingzuo'],
            required: ['xingzuo'],
        },
        parse: {
            mode: 'xingzuoDailyHtml',
        },
        replyMode: 'forward',
        forwardTitle: '星座今日运势',
        forwardNickname: '星座运势助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🌟 星座运势\n\n星座运势基于西方占星体系，以黄道十二星座和当日行星能量变化为基础，推演你在当天的综合、爱情、事业、财富与健康走势。每个星座对应不同的性格原型与能量节律，流日行星与本命星座形成互动后，会在现实层面体现为不同的机遇、挑战与情绪状态。\n\n用法说明：\n1) 输入一个星座名称即可查询（如白羊座、金牛座、双子座）；\n2) 支持中文全称与常见简称（如“处女座”“处女”）；\n3) 关键词后仅需一个参数，不要附加多余空格和符号。\n\n📌 指令格式：\n星座运势 星座\n\n💡 示例：\n星座运势 处女座\n星座运势 白羊',
        helpEntry: '🌟 星座运势 — 按星座查看今日综合/爱情/事业/财富/健康走势',
        helpCategory: '测算吉凶',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-shuzi-jixiong',
        keyword: ['数字吉凶', '数字测吉凶', '数字测算'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/jixiong/shuzi_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'shuzi={{shuzi}}',
        args: {
            mode: 'split',
            names: ['shuzi'],
            required: ['shuzi'],
        },
        parse: {
            mode: 'shuziHtml',
        },
        replyMode: 'forward',
        forwardTitle: '数字测算结果',
        forwardNickname: '数字吉凶助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔢 数字吉凶\n\n数字吉凶依据易学中的 81 数理体系进行推演。81 数理是在河洛数理与五行生克基础上总结提炼而来，通过数字对应的数理属性、吉凶象义及五行关系，分析该数字对运势、性格与现实选择（如号码、门牌、车牌等）的影响。\n\n用法说明：\n1) 输入任意一个数字即可测算；\n2) 常用于手机号、车牌号、门牌号、QQ 号等数字选择参考；\n3) 请输入纯数字，建议避免特殊符号与空格。\n\n📌 指令格式：\n数字吉凶 数字\n\n💡 示例：\n数字吉凶 3',
        helpEntry: '🔢 数字吉凶 — 81 数理推演数字吉凶与运势影响',
        helpCategory: '测算吉凶',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-tongziming-chaxun',
        keyword: ['童子命查询', '童子命', '查童子命'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/zhuanti/tongziming_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'tongzimingHtml',
        },
        replyMode: 'forward',
        forwardTitle: '童子命查询结果',
        forwardNickname: '童子命查询助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧒 童子命查询\n\n童子命查询以八字命理为基础，用四柱干支与纳音组合判断命局中是否带有“童子煞”特征。所谓童子命，传统命理中多指天界童子因缘入世，常见特征包括体弱多病、情感迟滞、人生阶段性坎坷等。该查询用于辅助识别命局类型与影响强弱，便于后续趋吉避凶与心态调整。\n\n排盘说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 八字命理日界通常按晚 23:00，23 点后系统按次日命盘计算；\n3) 若不确定出生时分，可不必精确到分钟。\n\n📌 指令格式：\n童子命查询 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n童子命查询 王羲之 男 公历 2005 12 23 8 11',
        helpEntry: '🧒 童子命查询 — 八字判断是否带童子命及影响说明',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-caiyun-yuce',
        keyword: ['财运预测', '财运测算', '三世书财运'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/yuce/caiyun_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'caiyunYuceHtml',
        },
        replyMode: 'forward',
        forwardTitle: '财运预测结果',
        forwardNickname: '财运预测助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💰 财运预测\n\n财运预测依据《三世书》的因果轮回理论，以出生年月日时为核心，推演命主今生的财运格局与财富走向。《三世书》起源于佛教《三世因果经》，以前世业因推今生果报，认为财运厚薄与前世积德行善密切相关，并非单纯由个人努力决定。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n财运预测 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n财运预测 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '💰 财运预测 — 依三世因果推演今生财运格局',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-mingyun-yuce',
        keyword: ['命运预测', '命运测算', '三世书命运'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/yuce/mingyun_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'mingyunHtml',
        },
        replyMode: 'forward',
        forwardTitle: '命运预测结果',
        forwardNickname: '命运预测助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔮 命运预测\n\n命运预测依据《三世书》的因果轮回理论，以出生年月日时为核心，推演命主今生的命运走向与人生提示。《三世书》起源于佛教《三世因果经》，拥有悠久的历史与演化，以前世业因推今生果报，认为命运并非偶然，而是三世因果的自然呈现。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n命运预测 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n命运预测 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🔮 命运预测 — 依三世因果推演今生命运走向',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-yinyuan-yuce',
        keyword: ['姻缘预测', '姻缘测算', '三世书姻缘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/yuce/yinyuan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'yinyuanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '姻缘预测结果',
        forwardNickname: '姻缘预测助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🌸 姻缘预测\n\n姻缘预测依据《三世书》的因果轮回理论，以出生年月日时为核心，推演命主今生的婚缘走向与夫妻缘分深浅。《三世书》起源于佛教《三世因果经》，以前世业因推今生果报，婚姻缘分亦在其中，认为婚缘并非偶然，而是三世因果的自然呈现。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n姻缘预测 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n姻缘预测 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🌸 姻缘预测 — 依三世因果推演今生婚缘走向',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhengyuan-huaxiang',
        keyword: ['正缘画像', '正缘预测', '真爱画像'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/yuce/zhengyuan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=2',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'zhengyuanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '正缘画像预测结果',
        forwardNickname: '正缘画像助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💞 正缘画像\n\n正缘画像以生辰八字为基础，从日柱所坐十神出发，推演命主正缘伴侣的五官气质、性格特质、家庭背景、事业财运及婚后相处模式，并结合奇门遁甲姻缘宫位推算正缘方位与结识契机，帮助命主建立对真爱的具体感知与心理画像。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n正缘画像 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n正缘画像 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '💞 正缘画像 — 推演正缘五官性格与姻缘方位指引',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-liudao-lunhui',
        keyword: ['六道轮回', '前世今生', '轮回预测'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/yuce/liudao_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=2',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'liudaoHtml',
        },
        replyMode: 'forward',
        forwardTitle: '六道轮回预测结果',
        forwardNickname: '六道轮回助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '☸️ 六道轮回\n\n六道轮回是佛教核心世界观之一，认为众生依业力在天道、阿修罗道、人道、地狱道、鬼道、畜生道六个层次中循环流转。前三道称"三善道"，后三道称"三恶道"，今生的善因恶果决定来世投入何道。本测算以生辰八字为基，推演命主的前世来处、今生所在与来世去向，可作自我修行与因果思考的参考。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n六道轮回 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n六道轮回 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '☸️ 六道轮回 — 以八字推演前世今生与来世去向',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-chenggu-lunming',
        keyword: ['称骨论命', '称骨算命', '称骨测算'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/chenggu_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'chengguHtml',
        },
        replyMode: 'forward',
        forwardTitle: '称骨论命结果',
        forwardNickname: '称骨论命助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '⚖️ 称骨论命\n\n称骨算命法由唐朝命理大师袁天罡所创，将一个人出生的年、月、日、时各自折算为对应的"骨重"两钱值，加总得出"称骨"总重，再据此查对命诗，判断命主的先天禀赋、福祸厚薄与一生走势。骨重越重，通常代表先天积累越厚，人生格局越高，是民间流传最广的算命方法之一。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n称骨论命 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n称骨论命 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '⚖️ 称骨论命 — 袁天罡称骨算命法推算先天命格',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-guxiang-lunming',
        keyword: ['骨相论命', '骨相测算', '骨相算命'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/guxiang_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'guxiangHtml',
        },
        replyMode: 'forward',
        forwardTitle: '骨相论命结果',
        forwardNickname: '骨相论命助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🦴 骨相论命\n\n骨相是中国古代流传已久的一支相术，认为人的骨骼框架在很大程度上代表先天命格。相骨之法以出生时辰推算命主所属骨形，不同骨相对应不同的性格禀赋、福祸走向与人生格局，是传统面相学与命理学结合的实用分支。\n\n用法说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 中国古代一个时辰约等于现在的两小时，精确到时辰范围即可；\n3) 若不确定出生分钟，可填 0。\n\n📌 指令格式：\n骨相论命 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n骨相论命 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🦴 骨相论命 — 依骨相推算先天命格与福祸走向',
        helpCategory: '运势预测',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-fengshui-xuankong',
        keyword: ['玄空飞星', '风水堪舆', '玄空排盘', '飞星排盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/fengshui/xuankong_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/fengshui/xuankong.html',
        },
        body: 'yun_model={{yun_model}}&shan_model={{shan_model}}&ti_model={{ti_model}}&long_model={{long_model}}&long_shui_kou={{long_shui_kou}}&ming_model={{ming_model}}&ming_liu_year={{ming_liu_year}}&ming_liu_month={{ming_liu_month}}&born_year={{born_year}}&sex={{sex}}',
        args: {
            mode: 'split',
            names: ['yun_model', 'shan_model', 'ti_model', 'long_model', 'long_shui_kou', 'ming_model', 'ming_liu_year', 'ming_liu_month', 'born_year', 'sex'],
            required: ['yun_model', 'shan_model', 'ti_model', 'long_model', 'ming_model', 'born_year', 'sex'],
            conditional: [
                {when: 'long_model', is: '1', require: ['long_shui_kou']},
                {when: 'ming_model', is: '1', require: ['ming_liu_year', 'ming_liu_month']},
            ],
        },
        parse: {
            mode: 'xuankongHtml',
        },
        replyMode: 'forward',
        forwardTitle: '玄空飞星结果',
        forwardNickname: '风水助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🏡 玄空飞星（风水堪舆）\n\n玄空飞星是以时间与空间变化为核心的风水理气体系，通过元运、山向、龙诀与命卦同参，观察住宅气场在不同宫位的吉凶流转。适用于住宅布局、开门纳气与长期居住环境优化参考。\n\n📌 指令格式：\n\n排龙诀为"是"、排命盘为"是"（最完整）：\n玄空飞星 元运 山向 用替 是 水口 是 流年 流月 宅主生年 性别\n\n排龙诀为"否"（跳过水口）：\n玄空飞星 元运 山向 用替 否 是 流年 流月 宅主生年 性别\n\n排命盘为"否"（跳过流年流月）：\n玄空飞星 元运 山向 用替 是 水口 否 宅主生年 性别\n\n两者皆"否"：\n玄空飞星 元运 山向 用替 否 否 宅主生年 性别\n\n🧭 参数说明：\n元运（三元九运）：每20年一运，目前是"九运"（2024-2043年）\n山向：房子的坐山与朝向。"壬山丙向"约等于坐北偏西北，朝南偏东南\n\n是否用替：一般选"否"。只有房子朝向非常偏时才用"是"\n是否排龙诀：看地基来龙吉凶。一般选"是"\n水口：房子附近水流或路口的位置，填与"山向"相同的字即可（如壬）；排龙诀为"否"时无需填写\n\n是否排命盘：看风水对你的影响。一般选"是"\n农历流年：你想测算的年份，如2026；排命盘为"否"时无需填写\n农历流月：你想测算的月份，如五月；排命盘为"否"时无需填写\n\n宅主生年：你的农历出生年份，如1995\n性别：男或女\n\n💡 示例：\n玄空飞星 九运 壬山丙向 否 是 壬 是 2026 五月 1995 男\n玄空飞星 九运 壬山丙向 否 否 否 1995 男',
        helpEntry: '🏡 玄空飞星 — 风水堪舆理气排盘（元运/山向/龙诀/命盘）',
        helpCategory: '风水堪舆',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-laohuangli-chaxun',
        keyword: ['黄历择日','老黄历查询', '老黄历', '黄历查询'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/zhuanti/laohuangli_result/id/{{date}}.html',
        method: 'GET',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            Referer: 'https://store.yuanfenju.com/zhuanti/zeshi.html',
        },
        args: {
            mode: 'split',
            names: ['date'],
            required: ['date'],
        },
        parse: {
            mode: 'laohuangliHtml',
        },
        replyMode: 'forward',
        forwardTitle: '老黄历查询结果',
        forwardNickname: '黄历助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '📜 老黄历查询\n\n老黄历查询用于查看指定日期的黄历信息，包含当日干支、农历日期、宜忌事项、五行冲煞、值神与吉神凶神等核心内容。适合在出行、办事、动土、嫁娶等场景做传统民俗参考。\n\n用法说明：\n1) 日期支持 YYYY-MM-DD（推荐），也支持 YYYY/MM/DD 或 YYYYMMDD；\n2) 也可输入“今天/今日”快速查询当天黄历；\n3) 结果仅供民俗参考，请结合实际安排。\n\n📌 指令格式：\n老黄历查询 日期\n\n💡 示例：\n老黄历查询 2026-05-12\n老黄历查询 今天',
        helpEntry: '📜 老黄历查询 — 查看指定日期的宜忌、五行、冲煞和值神',
        helpCategory: '测算吉凶',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zeshi-chaxun',
        keyword: ['吉日择时', '吉日查询', '择吉时查询', '黄道吉日查询', '择吉日查询'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/zhuanti/zeshi_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/zhuanti/zeshi.html',
        },
        body: 'future={{future}}&incident={{incident}}',
        args: {
            mode: 'split',
            names: ['future', 'incident'],
            required: ['future', 'incident'],
        },
        parse: {
            mode: 'zeshiHtml',
        },
        replyMode: 'forward',
        forwardTitle: '择吉时查询结果',
        forwardNickname: '择吉助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '📅 吉日择时\n\n择吉（择日）是中国传统民俗，通过查阅老黄历，选取最适合进行重要事宜的吉祥日期与吉时，趋吉避凶。查询时先取日之宜忌，再结合时辰宜忌综合判断。\n\n查询范围：\n  7天 / 15天 / 60天 / 90天\n\n支持的择吉事项：\n  搬家、装修、入宅、订婚、领证、求嗣、纳财\n  开市、交易、提车、置产、动土、出行、安葬\n  祭祀、祈福、沐浴、订盟、纳婿、修坟、破土\n  挂匾、栽种、入学、理发、会亲友、赴任、求医、治病\n\n📌 指令格式：\n吉日择时 查询范围 事项\n\n💡 示例：\n吉日择时 7天 搬家\n吉日择时 15天 领证\n吉日择时 60天 开市',
        helpEntry: '📅 吉日择时 — 查询未来吉日宜忌（搬家/结婚/开市等）',
        helpCategory: '测算吉凶',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-xingming-peidui',
        keyword: ['姓名配对', '名字配对', '缘份配对', '姓名缘份'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/peidui/xingming_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/peidui/xingming.html',
        },
        body: 'name_male={{name_male}}&name_female={{name_female}}',
        args: {
            mode: 'split',
            names: ['name_male', 'name_female'],
            required: ['name_male', 'name_female'],
        },
        parse: {
            mode: 'xingmingPeiduiHtml',
        },
        replyMode: 'forward',
        forwardTitle: '姓名配对结果',
        forwardNickname: '缘份配对助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💑 姓名配对\n\n姓名配对依据我国传统易学五行生克理论，对男女双方姓名进行分析，测算两人之间的缘份指数，帮助了解双方的姻缘契合程度。一切都是命中注定的，有注定的名字就会有注定的姻缘。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n姓名配对 男方姓名 女方姓名\n\n💡 示例：\n姓名配对 王小二 李大炮',
        helpEntry: '💑 姓名配对 — 五行生克推算两人姓名缘份指数',
        helpCategory: '缘份配对',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-shengri-peidui',
        keyword: ['生日配对', '生日缘份', '生日情侣配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/peidui/shengri_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/peidui/shengri.html',
        },
        body: 'month_male={{month_male}}&day_male={{day_male}}&month_female={{month_female}}&day_female={{day_female}}',
        args: {
            mode: 'split',
            names: ['month_male', 'day_male', 'month_female', 'day_female'],
            required: ['month_male', 'day_male', 'month_female', 'day_female'],
        },
        parse: {
            mode: 'shengriPeiduiHtml',
        },
        replyMode: 'forward',
        forwardTitle: '生日配对结果',
        forwardNickname: '缘份配对助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🎂 生日配对\n\n生日配对通过男女双方的公历生日对情侣关系进行测试，融合西方星相命理与现代性格学、人际关系学衍生而成，可帮助分析两人之间的性格契合度与缘份指数。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n生日配对 男方月 男方日 女方月 女方日\n\n💡 示例：\n生日配对 12 31 5 20',
        helpEntry: '🎂 生日配对 — 通过公历生日测算两人缘份指数',
        helpCategory: '缘份配对',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-xingzuo-peidui',
        keyword: ['星座配对', '星座缘份配对', '星座情侣配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/peidui/xingzuo_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/peidui/xingzuo.html',
        },
        body: 'xingzuo_male={{xingzuo_male}}&xingzuo_female={{xingzuo_female}}',
        args: {
            mode: 'split',
            names: ['xingzuo_male', 'xingzuo_female'],
            required: ['xingzuo_male', 'xingzuo_female'],
        },
        parse: {
            mode: 'xingzuoPeiduiHtml',
        },
        replyMode: 'forward',
        forwardTitle: '星座配对结果',
        forwardNickname: '缘份配对助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '⭐ 星座配对\n\n星座配对通过男女双方星座对情侣关系进行测试，融合西方星相命理与现代性格学、人际关系学衍生而成，分析双方在爱情、工作、金钱、健康四个维度的契合度，并给出恋爱建议与注意事项。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式（两种均可）：\n星座配对 男方星座 女方星座\n\n支持输入格式：\n- 带性别：处女男 白羊女\n- 不带性别（自动补充）：处女 白羊\n\n💡 示例：\n星座配对 处女 白羊\n星座配对 处女男 白羊女',
        helpEntry: '⭐ 星座配对 — 星座情侣配对（爱情/工作/金钱/健康）',
        helpCategory: '缘份配对',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-shengxiao-peidui',
        keyword: ['生肖配对', '生肖缘份配对', '生肖情侣配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/peidui/shengxiao_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/peidui/shengxiao.html',
        },
        body: 'shengxiao_male={{shengxiao_male}}&shengxiao_female={{shengxiao_female}}',
        args: {
            mode: 'split',
            names: ['shengxiao_male', 'shengxiao_female'],
            required: ['shengxiao_male', 'shengxiao_female'],
        },
        parse: {
            mode: 'shengxiaoPeiduiHtml',
        },
        replyMode: 'forward',
        forwardTitle: '生肖配对结果',
        forwardNickname: '缘份配对助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🐾 生肖配对\n\n生肖配对是根据十二属相之间相合、相冲、相克、相害、相生、相刑的规律而产生的一种婚姻配对法，可帮助分析情侣在爱情、工作、金钱、健康等方面的关系倾向。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n生肖配对 男方生肖 女方生肖\n\n支持输入：\n- 简写：猪 鼠\n- 常见写法：属猪 属鼠\n\n💡 示例：\n生肖配对 猪 鼠\n生肖配对 属猪 属鼠',
        helpEntry: '🐾 生肖配对 — 十二生肖婚配关系与缘份指数',
        helpCategory: '缘份配对',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-xuexing-peidui',
        keyword: ['血型配对', '血型缘份配对', '血型情侣配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/peidui/xuexing_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/peidui/xuexing.html',
        },
        body: 'xuexing_male={{xuexing_male}}&xuexing_female={{xuexing_female}}',
        args: {
            mode: 'split',
            names: ['xuexing_male', 'xuexing_female'],
            required: ['xuexing_male', 'xuexing_female'],
        },
        parse: {
            mode: 'xuexingPeiduiHtml',
        },
        replyMode: 'forward',
        forwardTitle: '血型配对结果',
        forwardNickname: '缘份配对助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🩸 血型配对\n\n血型配对通过男女双方血型测试情侣关系，不同血型组合会产生不同互动效果，可帮助分析两人关系中的优势与潜在磨合点。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n血型配对 男方血型 女方血型\n\n支持输入：\n- 字母：A / B / AB / O\n- 中文：A型 / B型 / AB型 / O型\n\n💡 示例：\n血型配对 B AB\n血型配对 B型 AB型',
        helpEntry: '🩸 血型配对 — 不同血型组合的情侣关系分析',
        helpCategory: '缘份配对',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-xingming-dafen',
        keyword: ['姓名打分', '姓名测分', '名字打分', '姓名评分'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/xingming/dafen_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/xingming/dafen.html',
        },
        body: 'shuzi={{shuzi}}',
        args: {
            mode: 'split',
            names: ['shuzi'],
            required: ['shuzi'],
        },
        parse: {
            mode: 'xingmingDafenHtml',
        },
        replyMode: 'forward',
        forwardTitle: '姓名打分结果',
        forwardNickname: '测名助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '📝 姓名打分\n\n姓名打分通过 81 数理原理对姓名进行测算，帮助分析姓名对运势、性格、事业与感情的影响。81 数理吉凶是在易学基础上总结提炼而来，并融合现代姓名灵数方法进行综合打分。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n姓名打分 姓名\n\n💡 示例：\n姓名打分 王小二',
        helpEntry: '📝 姓名打分 — 81 数理测算姓名吉凶与综合评分',
        helpCategory: '测算姓名',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-qiming-dafen',
        keyword: ['起名打分', '起名评分'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/home/xingming/qmdafen_result/{{surname}}.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/xingming/qmdafen.html',
        },
        body: 'surname={{surname}}&male_type={{qiming_gender}}&namewords={{qiming_words}}',
        args: {
            mode: 'split',
            names: ['surname', 'qiming_gender', 'qiming_words'],
            required: ['surname', 'qiming_gender', 'qiming_words'],
        },
        parse: {
            mode: 'qimingDafenHtml',
        },
        replyMode: 'forward',
        forwardTitle: '起名打分结果',
        forwardNickname: '测名助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧾 起名打分\n\n起名打分通过 81 数理原理生成并评估姓名，帮助分析姓名对运势、性格、事业与感情的影响。该方法在易学基础上总结提炼，并融合现代姓名灵数进行吉凶打分。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n起名打分 姓 性别(男/女) 字数(2/3)\n\n💡 示例：\n起名打分 李 男 3\n起名打分 王 女 2',
        helpEntry: '🧾 起名打分 — 按姓生成候选姓名并给出 81 数理评分',
        helpCategory: '测算姓名',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-gongsi-dafen',
        keyword: ['公司名打分', '公司名评分', '公司名测分'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/xingming/gongsi_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/xingming/gongsi.html',
        },
        body: 'shuzi={{shuzi}}',
        args: {
            mode: 'split',
            names: ['shuzi'],
            required: ['shuzi'],
        },
        parse: {
            mode: 'gongsiDafenHtml',
        },
        replyMode: 'forward',
        forwardTitle: '公司名打分结果',
        forwardNickname: '测名助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🏢 公司名打分\n\n公司名打分通过 81 数理原理对公司名进行测算，帮助分析公司名对运势与事业发展的影响。81 数理吉凶是在易学基础上总结提炼而来，并融合现代命名灵数方法进行综合评分。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n公司名打分 公司全名\n\n💡 示例：\n公司名打分 码渔',
        helpEntry: '🏢 公司名打分 — 81 数理测算公司名吉凶与评分',
        helpCategory: '测算姓名',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-online-qiming',
        keyword: ['姓名起名', '在线起名', '起名字'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/home/qiming/{{surname}}.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
            Referer: 'https://store.yuanfenju.com/xingming/qiming.html',
        },
        body: 'surname={{surname}}&male_type={{qiming_gender}}&namewords={{qiming_words}}',
        args: {
            mode: 'split',
            names: ['surname', 'qiming_gender', 'qiming_words'],
            required: ['surname', 'qiming_gender', 'qiming_words'],
        },
        parse: {
            mode: 'qimingListHtml',
        },
        replyMode: 'forward',
        forwardTitle: '在线起名结果',
        forwardNickname: '起名助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '📛 姓名起名\n\n姓名起名通过 81 数理原理进行姓名生成，帮助分析名字对运势、性格与事业等方面的影响。该方法在易学基础上总结提炼，并融合现代姓名灵数进行候选筛选。\n\n心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n姓名起名 姓 性别(男/女) 字数(2/3)\n\n💡 示例：\n姓名起名 李 男 3\n姓名起名 王 女 2',
        helpEntry: '📛 姓名起名 — 按姓氏生成姓名候选列表（支持性别/字数）',
        helpCategory: '测算姓名',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-demo-quote',
        keyword: ['玄学语录', '玄学一句'],
        matchMode: 'exact',
        url: 'https://api.yujn.cn/api/ysyl.php',
        method: 'GET',
        parse: {
            mode: 'text',
        },
        helpEntry: '🌀 玄学语录 — 随机一句玄学金句',
        helpCategory: '运势预测',
        replyTemplate: '🔮 {{result}}',
    },
    {
        name: 'xuanxue-demo-divination',
        enabled: false,
        keyword: '玄学占卜',
        matchMode: 'prefix',
        url: 'https://example.com/divination?q={{query}}',
        method: 'GET',
        parse: {
            mode: 'regex',
            pattern: '<div class="result">([\\s\\S]*?)</div>',
            flags: 'i',
            group: 1,
        },
        replyTemplate: '🧿 题目：{{query}}\n{{result}}',
    },
];

