import type {XuanxueRule} from './types.js';
import {buildHelpText} from './engine/help.js';

/**
 * 玄学插件规则注册表。
 * 新增规则时填写 helpEntry 字段即可自动出现在「玄学帮助」列表中。
 */
export const xuanxueRules: XuanxueRule[] = [
    {
        name: 'xuanxue-help',
        keyword: ['玄学帮助', '玄学指令', '算命帮助'],
        matchMode: 'exact',
        url: '',
        method: 'GET',
        parse: {mode: 'text'},
        // usage 由 buildHelpText() 在运行时动态生成，此处仅占位
        get usage() {
            return buildHelpText(xuanxueRules);
        },
    },
    {
        name: 'xuanxue-bazi-calc',
        keyword: ['八字测算', '八字测命'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/cesuan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=1&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'baziHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字测算结果',
        forwardNickname: '八字测算助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔮 八字测算\n\n八字算命可查询生辰八字、分析八字五行命理，出生日期支持公历和农历测算，测算结果仅供参考。\n\n八字，即生辰八字，是一个人出生时的干支历日期，四柱八字是算命方法中最正统的一种。中国古代一个时辰等于现在的两个小时，八字算命只需准确到时辰范围即可。\n\n📌 指令格式：\n八字测算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字测算 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🧬 八字测算 — 分析生辰八字、五行命理',
        helpCategory: '算命精选',
        replyTemplate:
            '🔮 八字测算结果\n姓名：{{name}}\n性别：{{sexInput}}\n历法：{{typeInput}}\n生辰：{{year}}-{{month}}-{{day}} {{hours}}:{{minute}}\n\n{{result}}\n\n💡 指令格式：八字测算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分',
    },
    {
        name: 'xuanxue-bazi-daily-fortune',
        keyword: ['八字每日运势', '每日八字运势', '八字今日运势'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/baziyunshi_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=1&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'baziHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字每日运势',
        forwardNickname: '每日运势助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '📆 八字每日运势\n\n输入生辰信息可测算当日运势，结果仅供参考，请自行体会其中的指示。\n\n测算简介：\n1) 可查询生辰八字与五行命理，支持公历和农历；\n2) 八字由年柱、月柱、日柱、时柱组成，共八个字；\n3) 一个时辰约等于现在两小时，通常只需精确到时辰范围。\n\n📌 指令格式：\n八字每日运势 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字每日运势 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '📆 八字每日运势 — 当日宜忌、幸运信息与分项运势',
        helpCategory: '算命精选',
        replyTemplate:
            '📆 八字每日运势\n姓名：{{name}}\n性别：{{sexInput}}\n历法：{{typeInput}}\n生辰：{{year}}-{{month}}-{{day}} {{hours}}:{{minute}}\n\n{{result}}\n\n💡 指令格式：八字每日运势 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分',
    },
    {
        name: 'xuanxue-bazi-hehun',
        keyword: ['八字合婚', '合婚测算', '合婚配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/hehun_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        // 格式：男方姓名 历法 年 月 日 时 分 女方姓名 历法 年 月 日 时 分
        body: 'male_name={{male_name}}&male_type={{male_type}}&male_year={{male_year}}&male_month={{male_month}}&male_day={{male_day}}&male_hours={{male_hours}}&male_minute={{male_minute}}&female_name={{female_name}}&female_type={{female_type}}&female_year={{female_year}}&female_month={{female_month}}&female_day={{female_day}}&female_hours={{female_hours}}&female_minute={{female_minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
            required: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
        },
        parse: {
            mode: 'heHunHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字合婚结果',
        forwardNickname: '八字合婚助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💑 八字合婚\n\n根据周易算命的方法，对男女双方的生辰八字进行配对合婚测算，分析两人命宫、年支、日干等多维度契合度，给出综合评分，仅供参考。\n\n📌 指令格式：\n八字合婚 男方姓名 历法(公历/农历) 年 月 日 时 分 女方姓名 历法 年 月 日 时 分\n\n💡 示例：\n八字合婚 王小二 公历 2005 12 23 8 37 李大炮 公历 2005 5 23 8 37',
        helpEntry: '💑 八字合婚 — 男女双方八字配对合婚评分',
        helpCategory: '算命精选',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-hepan',
        keyword: ['八字合盘', '合盘测算', '合盘配对'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/hepan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        // 格式：甲方姓名 历法 年 月 日 时 分 乙方姓名 历法 年 月 日 时 分
        body: 'male_name={{male_name}}&male_type={{male_type}}&male_year={{male_year}}&male_month={{male_month}}&male_day={{male_day}}&male_hours={{male_hours}}&male_minute={{male_minute}}&female_name={{female_name}}&female_type={{female_type}}&female_year={{female_year}}&female_month={{female_month}}&female_day={{female_day}}&female_hours={{female_hours}}&female_minute={{female_minute}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
            required: [
                'male_name', 'male_type', 'male_year', 'male_month', 'male_day', 'male_hours', 'male_minute',
                'female_name', 'female_type', 'female_year', 'female_month', 'female_day', 'female_hours', 'female_minute',
            ],
        },
        parse: {
            mode: 'hePanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字合盘结果',
        forwardNickname: '八字合盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🤝 八字合盘\n\n输入甲方和乙方的信息后，可进行本命卦合盘论吉凶。八字合盘并无绝对完美配对，50分以上通常可作为参考，结果仅供参考。\n\n📌 指令格式：\n八字合盘 甲方姓名 历法(公历/农历) 年 月 日 时 分 乙方姓名 历法 年 月 日 时 分\n\n💡 示例：\n八字合盘 王小二 公历 2005 12 23 8 37 李大炮 公历 2005 12 23 8 37',
        helpEntry: '🤝 八字合盘 — 双方本命卦与八字关系综合合盘评分',
        helpCategory: '算命精选',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-jingsuan',
        keyword: ['八字精算', '精算八字'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/jingsuan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn&sect=2',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'baziHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字精算结果',
        forwardNickname: '八字精算助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔮 八字精算\n\n在八字测算基础上进行更深度的命理分析，包含喜用神、大运流年、财运姻缘等全面解读，适合想深入了解命盘的用户，测算结果仅供参考。\n\n📌 指令格式：\n八字精算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字精算 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🔮 八字精算 — 深度命盘解读（喜用神/大运/流年）',
        helpCategory: '算命精选',
        replyTemplate:
            '🔮 八字精算结果\n姓名：{{name}}\n性别：{{sexInput}}\n历法：{{typeInput}}\n生辰：{{year}}-{{month}}-{{day}} {{hours}}:{{minute}}\n\n{{result}}\n\n💡 指令格式：八字精算 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分',
    },
    {
        name: 'xuanxue-bazi-paipan',
        keyword: ['八字排盘', '四柱排盘', '排八字'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/paipan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn&sect=1',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'paipanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '四柱八字排盘结果',
        forwardNickname: '八字排盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧮 四柱八字排盘\n\n将年月日时排成命盘，每个时间概念称为一柱，共四柱；每柱有天干地支两个字，共八个字，故称四柱八字排盘。\n\n排盘说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 八字日界线按晚上11时，若23时系统按次日排盘；\n3) 若不清楚出生分钟，可不必精确到分钟。\n\n📌 指令格式：\n八字排盘 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字排盘 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🧮 八字排盘 — 生成四柱命盘与大运排盘',
        helpCategory: '算命精选',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-jingpan',
        keyword: ['八字流盘', '四柱流盘', '八字精盘'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/jingpan_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&lang=zh-cn&sect=2',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute'],
        },
        parse: {
            mode: 'jingpanHtml',
        },
        replyMode: 'forward',
        forwardTitle: '四柱八字流盘结果',
        forwardNickname: '八字流盘助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🌊 四柱八字流盘\n\n将年月日时排成命盘，每个时间概念称为一柱，共四柱；每柱有天干地支两个字，共八个字，故称四柱八字流盘。\n\n流盘说明：\n1) 公历即阳历，农历即阴历，请按实际日期类型输入；\n2) 八字日界线按晚上11时，若23时系统按次日排盘；\n3) 若不清楚出生分钟，可不必精确到分钟。\n\n📌 指令格式：\n八字流盘 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分\n\n💡 示例：\n八字流盘 王羲之 男 公历 2005 12 23 8 37',
        helpEntry: '🌊 八字流盘 — 查看流年流月与胎命身精盘',
        helpCategory: '算命精选',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-bazi-caiyun',
        keyword: ['八字流年财运分析', '流年财运分析', '八字财运分析'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/index/caiyunfenxi_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'name={{name}}&sex={{sex}}&type={{type}}&year={{year}}&month={{month}}&day={{day}}&hours={{hours}}&minute={{minute}}&sect=2&liu_year={{liu_year}}&lang=zh-cn',
        args: {
            mode: 'split',
            names: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'liu_year'],
            required: ['name', 'sex', 'type', 'year', 'month', 'day', 'hours', 'minute', 'liu_year'],
        },
        parse: {
            mode: 'caiyunHtml',
        },
        replyMode: 'forward',
        forwardTitle: '八字流年财运分析结果',
        forwardNickname: '流年财运助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💰 八字流年财运分析\n\n输入生辰与目标年份，可测算流年财运等级、财星显隐、漏财风险与每月财运建议，结果仅供参考。\n\n测算简介：\n1) 提供目标年份财运综合评估、风险提示与月度建议；\n2) 以生辰八字与流年干支关系为核心，分析财星强弱与身强身弱适配；\n3) 八字通常精确到时辰范围即可，无需过度纠结分钟。\n\n📌 指令格式：\n八字流年财运分析 姓名 性别(男/女) 历法(公历/农历) 年 月 日 时 分 目标年份\n\n💡 示例：\n八字流年财运分析 王羲之 男 公历 2005 12 23 8 37 2026',
        helpEntry: '💰 八字流年财运分析 — 年度财运评分与每月投资提示',
        helpCategory: '算命精选',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-meiri',
        keyword: ['每日一占', '每日占卜', '小六壬占卜'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/zhanbu/meiri_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '每日一占结果',
        forwardNickname: '占卜助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🧿 每日一占\n\n卜卦方法：静默一分钟，心念集中于所测之事（爱情/事业/健康等），然后心念一动，发送指令后查看卦辞并体会吉凶指示。\n\n摇卦简介：\n1) 每日占卜使用小六壬占卜法，摇卦贵在随机而动；\n2) 不急不占，无事不占，不动不占；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n每日一占\n\n💡 示例：\n每日一占',
        helpEntry: '🧿 每日一占 — 小六壬随机摇卦解读',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-taluo',
        keyword: ['塔罗牌占卜', '塔罗占卜', '塔罗牌'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/zhanbu/taluo_result/id/0.html',
        method: 'GET',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '塔罗牌占卜结果',
        forwardNickname: '塔罗占卜助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🔮 塔罗牌占卜\n\n塔罗牌是西方古老占卜工具，被称为“大自然的奥秘库”。此玩法为单张牌占卜，适合快速查看当前主题指示。\n\n塔罗牌简介：\n1) 大阿卡那共 22 张，常用于观察阶段性主线与运势方向；\n2) 单张牌占卜法简单直观，适用于多数主题；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n塔罗牌占卜\n\n💡 示例：\n塔罗牌占卜',
        helpEntry: '🃏 塔罗牌占卜 — 单张塔罗牌解读与神谕提示',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-yaoguai',
        keyword: ['摇卦占卜', '摇卦', '金钱卦', '易经占卜'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/zhanbu/result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '摇卦占卜结果',
        forwardNickname: '摇卦助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🪙 摇卦占卜\n\n金钱卦是六爻占卜中的简易算法，以铜钱随机摇卦，得六十四卦之一，用以占卜吉凶。\n\n卜卦方法：\n1) 静默一分钟，心念集中于所测之事（爱情/事业/健康等）；\n2) 心念一动，发送指令即随机掷出金钱卦；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n摇卦占卜\n\n💡 示例：\n摇卦占卜',
        helpEntry: '🪙 摇卦占卜 — 随机掷出六十四卦，查看卦辞吉凶',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-zhanbu-zhiwen',
        keyword: ['指纹占卜', '指纹测算'],
        matchMode: 'prefix',
        url: 'https://store.yuanfenju.com/zhanbu/zhiwen_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'muzhi={{muzhi}}&shizhi={{shizhi}}&zhongzhi={{zhongzhi}}&wumingzhi={{wumingzhi}}&xiaozhi={{xiaozhi}}',
        args: {
            mode: 'regex',
            // 匹配5位由0/1组成的字符串，如：01010 或 0 1 0 1 0
            pattern: '^\\s*([01])[\\s,，]*([01])[\\s,，]*([01])[\\s,，]*([01])[\\s,，]*([01])\\s*$',
            names: ['muzhi', 'shizhi', 'zhongzhi', 'wumingzhi', 'xiaozhi'],
            required: ['muzhi', 'shizhi', 'zhongzhi', 'wumingzhi', 'xiaozhi'],
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '指纹占卜结果',
        forwardNickname: '指纹占卜助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🖐 指纹占卜\n\n根据指纹形状测算性格与命运，男性测左手，女性测右手。指纹分两类：\n• 箩纹（斗纹）= 0 — 同心圆/螺旋状，外围闭合\n• 簸箕纹（流纹）= 1 — 开口如高山流水状\n\n📌 指令格式：\n指纹占卜 大拇指 食指 中指 无名指 小指\n（每指输入 0=箩纹 或 1=簸箕纹，可连写或空格分隔）\n\n💡 示例：\n指纹占卜 01010\n指纹占卜 0 1 0 1 0',
        helpEntry: '🖐 指纹占卜 — 根据五指指纹形状解读性格与命运',
        helpCategory: '算卦占卜',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-guanyin',
        keyword: ['观音灵签', '观音抽签', '观音签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/guanyin_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '观音灵签结果',
        forwardNickname: '观音灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '🪷 观音灵签\n\n抽签前双手合十，默念【救苦救难观音菩萨】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽取灵签并查看签辞。\n\n抽签简介：\n1) 观音灵签为民间常见签种，共百签，各地签文略有差异但解意大致相通；\n2) 观世音菩萨象征慈悲与智慧，签辞多用于启示与劝勉；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n观音灵签\n\n💡 示例：\n观音灵签',
        helpEntry: '🪷 观音灵签 — 抽取观音签辞并查看解签信息',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-lingqian-yuelao',
        keyword: ['月老灵签', '月老抽签', '月老签'],
        matchMode: 'exact',
        url: 'https://store.yuanfenju.com/lingqian/yuelao_result.html',
        method: 'POST',
        headers: {
            Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Content-Type': 'application/x-www-form-urlencoded',
        },
        parse: {
            mode: 'zhanbuHtml',
        },
        replyMode: 'forward',
        forwardTitle: '月老灵签结果',
        forwardNickname: '月老灵签助手',
        forwardAvatarUrl: 'https://bkimg.cdn.bcebos.com/pic/8d5494eef01f3a292df5593c5d7fab315c6035a8d6b4?x-bce-process=image/format,f_auto/quality,Q_70/resize,m_lfit,limit_1,w_536',
        usage: '💘 月老灵签\n\n抽签前双手合十，默念【月下老人诚求指示】三遍，心念集中于所测之事（爱情/事业/健康等），随后发送指令抽签并查看签辞。\n\n抽签简介：\n1) 月老灵签为民间常见签种，共百签，签文流传久远，各地略有差异但解意大致相通；\n2) 月下老人是民间传说中的婚姻之神（红喜神/媒神），多用于姻缘指引；\n3) 心诚则灵，测算结果仅供参考。\n\n📌 指令格式：\n月老灵签\n\n💡 示例：\n月老灵签',
        helpEntry: '💘 月老灵签 — 抽取月老签辞并查看解签提示',
        helpCategory: '灵签抽签',
        replyTemplate: '',
    },
    {
        name: 'xuanxue-demo-quote',
        keyword: ['玄学语录', '玄学一句'],
        matchMode: 'exact',
        url: 'https://api.yujn.cn/api/ysyl.php',
        method: 'GET',
        parse: {
            mode: 'text',
        },
        helpEntry: '🌀 玄学语录 — 随机一句玄学金句',
        helpCategory: '算命精选',
        replyTemplate: '🔮 {{result}}',
    },
    {
        name: 'xuanxue-demo-divination',
        enabled: false,
        keyword: '玄学占卜',
        matchMode: 'prefix',
        url: 'https://example.com/divination?q={{query}}',
        method: 'GET',
        parse: {
            mode: 'regex',
            pattern: '<div class="result">([\\s\\S]*?)</div>',
            flags: 'i',
            group: 1,
        },
        replyTemplate: '🧿 题目：{{query}}\n{{result}}',
    },
];

