/** 微信视频消息发送默认配置。 */
export const DEFAULT_VIDEO_THUMB_BASE64 =
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO5W0YQAAAAASUVORK5CYII=';

/** 默认视频时长（秒）。 */
export const DEFAULT_VIDEO_DURATION = 12;

